### ISSUE TITLE
Vocal Design

### ISSUE THREAD

**Issue by Echo82** [athaun/Eclipse-OS#1]
(Let me introduce myself, my name is Ethan.  First of all, let me just say that I am not really on the EOS team and don't think I have the time to dedicate to that, but I am a friend of Asher and thought I would try to help out here and there when I have the time.)

This is not so much a code issue as a design one: What should we do with Vocal?  Should we change the design of Vocal or try to remake it as-is?  Here is a version of Vocal I have made on KA that is different in its design, but I don't know if this is what we would want to use.  
Link: https://www.khanacademy.org/computer-programming/spin-off-of-vocal-personal-assistant/6039598435696640

Anyway, this is a something that we should probably think about before putting in the long hours to make Vocal anew.

**Comment by athaun** [comment]
first point - for those that are curious, I do know Echo, and I added him as a collaborator.
response - good question, I think we will end up rewriting vocal because it was originally designed for hard coded answers. Vocal has advanced past that, and I think it should be rewritten with new, clean, and smart code.
